### ISSUE TITLE
Error running app: Default activity not found

### ISSUE THREAD

**Issue by IAmSagarModi** [ashokgujju/QuiphTask#1]
@ashokgujju 
The app doesn't have a default activity, hence it is not getting installed on a device.
It also doesn't have the necessary permissions to carry out the given task.

**Comment by ashokgujju** [comment]
@sagarmodi91 It doesn't require an activity. 
In Android Studio, go to Edit Run/Debug Configurations > General, set "Launch Options > Launch" as "Nothing"
In Phone, go to Settings > Accessibility, enable "QuiphTask"
